[build]
  command = "echo 'Skipping OQS rebuild for graceful fallback deployment' && npm run build:plugin"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10"
  # Force rebuild of native dependencies for Linux x64
  npm_config_target_platform = "linux"
  npm_config_target_arch = "x64"
  npm_config_cache = "/opt/buildhome/.npm"
  # OQS library environment variables
  OQS_ENABLE_KEM_ML_KEM = "ON"
  OQS_ENABLE_SIG_DILITHIUM = "OFF"
  OQS_ENABLE_SIG_FALCON = "OFF"
  OQS_ENABLE_SIG_SPHINCS = "OFF"
  # Memory optimization for serverless (removed --optimize-for-size as it's not allowed)
  NODE_OPTIONS = "--max-old-space-size=1536 --enable-source-maps"
  # Build optimization
  NETLIFY_USE_ESBUILD = "true"
  ESBUILD_FLAGS = "--bundle --minify --tree-shaking"
  # Native dependencies
  PYTHON = "python3"
  CC = "gcc"
  CXX = "g++"
  # OQS build optimization
  CMAKE_BUILD_TYPE = "Release"
  OQS_BUILD_ONLY_LIB = "ON"
  # Performance tuning
  UV_THREADPOOL_SIZE = "8"
  # Security - API Key for decryption endpoint (set in Netlify dashboard)
  PQLS_API_KEY = "dev-api-key-12345-change-in-production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  # External node modules that should not be bundled (removed OQS to reduce size)
  external_node_modules = []
  # Removed OQS library files to stay under 250MB limit
  included_files = []

[functions."*"]
  # Memory and timeout optimization for post-quantum operations
  memory = 1536
  timeout = 30
  runtime = "nodejs18.x"

[functions.encrypt]
  memory = 1536
  timeout = 30
  runtime = "nodejs18.x"

[functions.decrypt]
  memory = 1536
  timeout = 30
  runtime = "nodejs18.x"

[functions.generate-keypair]
  memory = 1024
  timeout = 20
  runtime = "nodejs18.x"

[functions.monitor]
  memory = 512
  timeout = 15
  runtime = "nodejs18.x"

[functions.status]
  memory = 512
  timeout = 15
  runtime = "nodejs18.x"

[dev]
  framework = "#static"
  port = 8888
  # Development environment variables
  [dev.env]
    NODE_OPTIONS = "--max-old-space-size=1024"
    OQS_ENABLE_KEM_ML_KEM = "ON"
    OQS_ENABLE_SIG_DILITHIUM = "OFF"
    OQS_ENABLE_SIG_FALCON = "OFF"
    OQS_ENABLE_SIG_SPHINCS = "OFF"
    UV_THREADPOOL_SIZE = "4"
    # Development API key (replace with secure key in production)
    PQLS_API_KEY = "dev-api-key-12345-change-in-production" 